export const TRADE_PROFESSIONALITIES = [
  'Electrician',
  'Plumber',
  'HVAC Technician',
  'Carpenter',
  'Painter',
  'Roofer',
  'Mason / Bricklayer',
  'Flooring Specialist',
  'Tile Setter',
  'Welder',
  'Landscaper',
  'Pest Control',
  'Locksmith',
  'Glazier / Window Installer',
  'Drywall / Plasterer',
  'Insulation Specialist',
  'Concrete & Foundation',
  'Pool & Spa Technician',
  'Solar Panel Installer',
  'Garage Door Specialist',
  'Handyman',
  'Demolition Contractor',
];

export const CONTRACTOR_EXPERTISE = [
  'Residential Construction',
  'Commercial Construction',
  'Industrial Construction',
  'Renovation & Remodeling',
  'New Construction',
  'Additions & Extensions',
  'Roofing & Waterproofing',
  'Foundation & Structural',
  'Interior Fit-Out',
  'Historic Restoration',
  'Green / Sustainable Building',
  'Prefabricated / Modular Building',
];
